Fix passing host to in headers
Lawouach/WebSocket-for-Python pull request #268
Opened 2021-04-07 08:06 UTC by liuchong

In `WebSocketBaseClient`, there is a hardcoded `Host` header. This pull request will let it use `Host` in the passed in extra headers, and if it is not exists in extra headers, will use the origin logic to set `Host`.

2024-12-24 09:02 UTC, auvipy requested changes

2024-12-24 09:02 UTC, auvipy commented on ws4py/client/__init__.py
> +
```suggestion


```

2025-01-24 09:47 UTC, liuchong commented
Ok, I've added a unit test for this, please check @auvipy 👀

2025-01-29 05:45 UTC, auvipy requested changes
think we should also update the relevant docs, what do you think?

2025-05-07 12:02 UTC, auvipy approved these changes

2025-05-07 12:02 UTC, merged